FROM <<REPLACE_WITH_DOCKER_IMAGE_FROM>>

RUN apt update
RUN apt install -y sudo
RUN apt install -y nano
RUN if !(getent passwd "<<REPLACE_WITH_DOCKER_USER>>" > /dev/null 2>&1); then adduser --disabled-password --gecos "" <<REPLACE_WITH_DOCKER_USER>>; fi
COPY sudoers /etc

COPY files /

RUN runuser -l <<REPLACE_WITH_DOCKER_USER>> -c "bash /install.bash"
RUN rm /install.bash

CMD runuser -l <<REPLACE_WITH_DOCKER_USER>> -c "bash /start.bash & sleep infinity"